### ISSUE TITLE
Autolink should read until whitespace

### ISSUE THREAD

**Issue by towerofnix** [nanaian/mrk#1]
Currently it reads until `' '`: https://github.com/heyitsmeuralex/mrk/blob/05f4d98f8e707a8c85bf99c4ac42610ccf9b688f/mrk.js#L264-L265

Obviously any whitespace will stop a link. Autolink should probably read until any whitespace (or at least space, newline).

**Comment by bates64** [comment]
PR welcome for this - should be decently easy?

**Comment by joker314** [comment]
It'd be awesome if `readUntil` accepted regular expressions. That way, it would be easier to make extensions to mrk, and the fix for this issue would be replacing `' '` with `/\s/`. :)

**Comment by bates64** [comment]
👍
